nelmio_api_doc:
    documentation:
        info:
            title: MyHammer API
            description: API Doc for MyHammer API
            version: 1.0.0

    areas:
        path_patterns:
        - ^/(?!api/doc$)
