parameters:
    locale: 'en'

imports:
- { resource: 'exception_map.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MyHammer\Api\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    MyHammer\Api\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    MyHammer\Api\Service\ExceptionTransformerService:
        arguments:
            $exceptionMap: '%exception_map%'

    MyHammer\Api\EventSubscriber\ExceptionSubscriber:
        arguments:
            $environment: '%kernel.environment%'
